### ISSUE TITLE
app stops working when google icon logo is clicked 

### ISSUE THREAD

**Issue by papppyo** [cabinjs/cabin#103]
#### Expected behavior 

I should be able to add cluster from my google account

#### Actual behavior

I was unable to add cluster from my gmail account  each time I try to ,the app stops working it force closes 

#### How to reproduce

*Download 

*Install 

*Launch 

*Click on add cluster 

*Finally ,if you have a google account on your phone it will automatically want to use any of the google accounts you have ,so just click on the gmail app Logo 
and wait for the error..

*Cabin 0.5.0
*Android 7.0 nougat 

#### Recording of the bug 

https://youtu.be/joZ2NcztWE4

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@pappy/app-stops-working-when-google-icon-logo-is-clicked">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by niftylettuce** [comment]
Not related to this project
