### ISSUE TITLE
use sendBeacon in browser

### ISSUE THREAD

**Issue by niftylettuce** [cabinjs/cabin#113]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
https://caniuse.com/#feat=beacon
https://github.com/miguelmota/Navigator.sendBeacon (see if https://github.com/miguelmota/Navigator.sendBeacon/pull/10 is merged)

**Comment by kronicker** [comment]
@niftylettuce If it is convenient for you, I published fixes from https://github.com/miguelmota/Navigator.sendBeacon/pull/10 as a separate npm package [sendbeacon-polyfill](https://www.npmjs.com/package/sendbeacon-polyfill) so feel free to use it.
Bear in mind that if original package author [miguelmota](https://github.com/miguelmota) decides to accept the PR and would prefer that, I might stop maintaining mine and depracate it in favour of his, original one.

**Comment by niftylettuce** [comment]
not going to use this
