### ISSUE TITLE
add option to exclude app info

### ISSUE THREAD

**Issue by defreek** [cabinjs/cabin#129]

**Comment by niftylettuce** [comment]
@defreek 	you can now do this using the `appInfo` (Boolean) option in the latest version of `axe@4.0.3`.  I have bumped this `axe` dependency in `cabin` and you can do this now in the latest version of `cabin@5.0.2`.

See `appInfo` option here <https://github.com/cabinjs/axe#options>.  You would create a new Cabin instance with `const cabin = new Cabin({ axe: { appInfo: false } });` to take advantage of this option.

P.S. You might like my new framework, https://lad.js.org - version 0.1.0 is out (albeit a lot of TODO's still, but 1.0.0 is coming soon)
