### ISSUE TITLE
req.logger/res.logger `silent` option in Express?

### ISSUE THREAD

**Issue by armenr** [cabinjs/cabin#131]
I have a healthcheck route for my loadbalancers to ping our core service.

I'd like to pass something like `res.logger({ axe: {silent: true }})` to the route, in order to silence that specific message.

Is there any such ignore pattern for Express + CabinJS to achieve this on a specific route, rather than injecting a logger into every route? That is to say, is there an easy opt-out on a per-route basis, with a globally configured logger

Thank you! :)

**Comment by armenr** [comment]
I tried to experiment with req.logger, but it seems by setting the logger level in the route, it set it to be global, and now none of the requests to any of my proxied routes are working.

Server file below:

```

**Comment by armenr** [comment]
Thank you, I'll look into your suggestions and post back. :)

**Comment by smashah** [comment]
@niftylettuce is it possible to return `undefined` or `void` for the message function to force the logger to ignore it?

**Comment by titanism** [comment]
So basically we'd change this:

```diff
  // upon completion of a response we need to log it
  onFinished(res, (err) => {
    if (err) logger.error(err);
    let level = 'info';
    if (res.statusCode >= 500) level = 'error';
    else if (res.statusCode >= 400) level = 'warn';
    const message = this.config.message({
      level,
      req: request,
      res,
      ...(isExpress ? {} : { ctx: args[0] })
    });
    
+    //
+    // return early if message value returned was null or undefined
+    // <https://github.com/cabinjs/cabin/issues/131#issuecomment-1315122082>
+    //
+    if (message === null || typeof message === 'undefined') return;
    
    if (err) logger[level](message, { err });
    else logger[level](message);
  });
```

**Comment by smashah** [comment]
@titanism I know based on your docs `undefined` or `null` are invalid returns for the function and it seems as though it's as simple as your proposal but, upon second thought, there may be edge cases for some users where `undefined` or `null` are useful messages.

Maybe there can be a second parameter to the message function that is an ignore trigger?

```js
  // upon completion of a response we need to log it
  onFinished(res, (err) => {
    if (err) logger.error(err);
    let level = 'info';
    if (res.statusCode >= 500) level = 'error';
    else if (res.statusCode >= 400) level = 'warn';
    let ignore = false;

    const message = this.config.message({
      level,
      req: request,
      res,
      ...(isExpress ? {} : { ctx: args[0] })
    }, ()=>{ignore=true});

    if(ignore) return;
    if (err) logger[level](message, { err });
    else logger[level](message);
  });
```

It may prevent a regression and future headaches.

I'm happy for either implementation though. Thanks for the consideration.

**Comment by titanism** [comment]
I think the approach where if the message is undefined or null it would be useful.  Let's do that.  Implementing it now, one moment.

**Comment by titanism** [comment]
v10.0.3 released with this support!

https://github.com/cabinjs/cabin/releases/tag/v10.0.3

**Comment by smashah** [comment]
Thanks for the rapid turnaround @titanism much appreciated!
