### ISSUE TITLE
How to make the log tiny (compact mode)

### ISSUE THREAD

**Issue by weihsth** [cabinjs/cabin#151]
Hey guys,

thank you for this great tool. But I did not find out, how it's possible to shrink the output.. it's nearly impossible to debug something in the console.

I read the documentation, but I am not able to get it.

I want to have somthing like:

```
import * as morganLogger from 'morgan';
app.use(morganLogger(process.env.LOGGING_FORMAT || 'combined'));
```

Is that possible without adding another X dependencies?

That's what I have atm:

```
app.use(requestReceived);
app.use(responseTime());
app.use(requestId());
app.use(cabin.middleware);
```

**Comment by niftylettuce** [comment]
You can use the environment variables `SHOW_META`, `SHOW_META_APP`, and `OMIT_META_FIELDS`.

You most likely would want to set `SHOW_META_APP=false` to disable the application parsed information.

**Comment by niftylettuce** [comment]
Reference Axe documentation (ref #152)
