### ISSUE TITLE
[feat] Switch between apache-friendly and JSON output

### ISSUE THREAD

**Issue by abetoots** [cabinjs/cabin#156]
## Describe the feature

This in relation to #132 . Currently, message always returns an apache-friendly string log. Can we add support for returning the message as JSON?

Ideally, if we are already using Axe, since it provides a normalized standard of logging, we could pass the JSON as metadata, like in [here ](https://github.com/cabinjs/cabin/blob/f378aadc37f507c5bbe481cb57378a1520f541d1/src/middleware.js#L88): 
` logger[level](message, metadata);`

What I want as JSON would be this

![cabin](https://user-images.githubusercontent.com/45987443/203733717-ee7a910b-9e94-46ee-93f0-f9573de589b1.png)

Use case:
So I can send logs to JSON friendly centralized logging systems like DataDog or Papertrail.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by titanism** [comment]
@abetoots have you updated to the latest major versions of cabin and axe?  we now have support for pre and post hooks.  you could make an async post hook to send log data as json to datadog, papertrail, wherever.

https://github.com/cabinjs/cabin#send-logs-to-an-http-endpoint

https://github.com/cabinjs/axe/#send-logs-to-sentry

**Comment by titanism** [comment]
@abetoots note that the cabin middleware calls the logger (axe) with the request parsed, so you could make a post hook to `JSON.stringify` or use a package such as `fast-safe-stringify` to send `err`, `message`, and `meta` to datadog

@abetoots we have added Datadog and Papertrail examples for you, see these below references:

- https://github.com/cabinjs/cabin#send-logs-to-datadog &rarr; https://github.com/cabinjs/axe#send-logs-to-datadog
- https://github.com/cabinjs/cabin#send-logs-to-papertrail &rarr; https://github.com/cabinjs/axe#send-logs-to-papertrail
