### ISSUE TITLE
[feat] TypeScript support? (Again)

### ISSUE THREAD

**Issue by denizdogan** [cabinjs/cabin#159]
## Describe the feature

#143 was closed and locked in 2020. It's 2023 now, and most real-world applications rely heavily on TypeScript these days. Is there any chance that you changed your mind on this?

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by basdp** [comment]
This is the reason I can't use Cabin. I won't use a library that doesn't provide typescript types.

**Comment by oldium** [comment]
This is the smallest problem actually. Just after installing with npm, it reported:

```
npm WARN deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 72 packages, and audited 703 packages in 7s

164 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (3 low, 3 high)
```

This is a no-go for any serious project.

**Comment by titanism** [comment]
If someone submits and maintains a PR for TS we would consider it.

We're using it in production just fine @forwardemail and we don't use TS anywhere in the company and things are working just fine.

**Comment by basdp** [comment]
I'm not going to do the work only for consideration, sorry. I need a bit more certainty.

**Comment by kevinclarkadstech** [comment]
Yes this will surely prevent me from adopting this library...who does not publish a library without TypeScript definitions these days?

**Comment by kevinclarkadstech** [comment]
> This is the reason I can't use Cabin. I won't use a library that doesn't provide typescript types.

Not sure why this was "Marked spam"...this is a very constructive comment.  It's the most popular language these days.  I can understand internal apps being vanilla JS but if you want to get people to use your product then it is a must.

**Comment by titanism** [comment]
as mentioned feel free to PR, you could use AI to contribute if needed
